version: 2
jobs:
  deploy:
    docker:
       - image: circleci/ruby:2.3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - gem-{{ .Revision }}
      - run:
          name: push to rubygems
          command: bin/deploy
  build:
    docker:
       - image: circleci/ruby:2.3
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: run default rake target
          command: |
            bundle exec rake
      - save_cache:
          paths:
            - pkg
          key: gem-{{ .Revision }}
      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: pkg

workflows:
  version: 2
  un-tagged-build:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^v.*/
  tagged-build:
    jobs:
      - deploy:
          requires:
            - build
      - build:
          filters:
            branches:
              ignore: /^v.*/
            tags:
              only: /^v.*/
